
FFTW.js:	
	emcc -O3 \
	     --memory-init-file 0 \
	     -s NO_FILESYSTEM=1 \
	     -s MODULARIZE=1 \
	     -s PRECISE_F32=1 \
	     -s EXPORT_NAME="'FFTWModule'" \
	     -s EXPORTED_FUNCTIONS="['_fftwf_plan_r2r_1d','_fftwf_plan_dft_r2c_1d','_fftwf_plan_dft_c2r_1d','_fftwf_destroy_plan','_fftwf_execute']" \
	     -o FFTW.js \
	     fftw-3.3.4/.libs/libfftw3f.a

clean:
	rm -f FFTW.js

